# Generated by Django 5.0.6 on 2024-06-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigator_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='basic_servey_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IRM', models.BooleanField(choices=[(True, 'IRM'), (False, 'NON-IRM')], default=False)),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('category', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('gender', models.BooleanField(choices=[(True, 'male'), (False, 'female')], default=True)),
                ('village', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('taluka', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('district', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('date_of_sowing', models.DateField()),
                ('spacing', models.CharField(max_length=100)),
                ('cotton_variety', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('previous_year_crop_grown', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('causes', models.BooleanField(choices=[(True, 'irrigation'), (False, 'rainfed')], default=False)),
                ('last_year_crop_extended', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('soil_type', models.CharField(choices=[('shallow', 'Shallow'), ('medium', 'Medium'), ('heavy', 'Heavy')], max_length=20)),
                ('crop_rotation_followed', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('advisory_received_from', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('recorded_file', models.FileField(blank=True, default='', null=True, upload_to='recorded_files/')),
                ('geolocations', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
    ]
