# Generated by Django 5.0.6 on 2024-07-01 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investigator_app', '0002_basic_servey_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basic_servey_info',
            name='gender',
        ),
    ]
