# Generated by Django 5.0.6 on 2024-07-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigator_app', '0003_remove_basic_servey_info_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basic_servey_info',
            name='spacing',
        ),
        migrations.AddField(
            model_name='basic_servey_info',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='basic_servey_info',
            name='plant_distance',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='basic_servey_info',
            name='row_distance',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
