# Generated by Django 5.0.6 on 2024-07-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigator_app', '0004_remove_basic_servey_info_spacing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic_servey_info',
            name='total_farmers_ecommunication',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
