# Generated by Django 5.0.6 on 2024-07-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigator_app', '0005_basic_servey_info_total_farmers_ecommunication'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic_servey_info',
            name='user_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
