# Generated by Django 5.0.6 on 2024-07-04 08:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigator_app', '0006_basic_servey_info_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic_servey_info',
            name='date_of_servey',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
