# Generated by Django 5.0.6 on 2024-07-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigator_app', '0007_basic_servey_info_date_of_servey'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic_servey_info',
            name='year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
