# Generated by Django 5.0.6 on 2024-07-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigator_app', '0008_basic_servey_info_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basic_servey_info',
            name='date_of_servey',
        ),
        migrations.AddField(
            model_name='basic_servey_info',
            name='servey_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
