# Generated by Django 5.0.6 on 2024-07-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigator_app', '0009_remove_basic_servey_info_date_of_servey_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepresentedPhotograph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief_activity_description_1', models.TextField(blank=True, null=True)),
                ('brief_activity_description_2', models.TextField(blank=True, null=True)),
                ('brief_activity_description_3', models.TextField(blank=True, null=True)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image_6', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
