# Generated by Django 5.0.6 on 2024-07-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigator_app', '0010_representedphotograph'),
    ]

    operations = [
        migrations.AddField(
            model_name='representedphotograph',
            name='date_field',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='representedphotograph',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='representedphotograph',
            name='month',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='representedphotograph',
            name='name_of_investigator',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='representedphotograph',
            name='physical_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='representedphotograph',
            name='user_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='representedphotograph',
            name='week',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='representedphotograph',
            name='year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
