# Generated by Django 5.0.6 on 2024-07-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigator_app', '0011_representedphotograph_date_field_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='', max_length=100)),
                ('date_field', models.DateField(blank=True, null=True)),
                ('physical_date', models.CharField(blank=True, max_length=100, null=True)),
                ('week', models.CharField(blank=True, max_length=100, null=True)),
                ('name_of_investigator', models.CharField(blank=True, max_length=100, null=True)),
                ('month', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('number_sucking', models.CharField(blank=True, max_length=100, null=True)),
                ('number_bollworms', models.CharField(blank=True, max_length=100, null=True)),
                ('cost_spray_sucking', models.CharField(blank=True, max_length=100, null=True)),
                ('cost_spray_bollworms', models.CharField(blank=True, max_length=100, null=True)),
                ('pesticide_reduction_cost', models.CharField(blank=True, max_length=100, null=True)),
                ('pesticide_reduction_volume', models.CharField(blank=True, max_length=100, null=True)),
                ('picking_1', models.CharField(blank=True, max_length=100, null=True)),
                ('picking_2', models.CharField(blank=True, max_length=100, null=True)),
                ('picking_3', models.CharField(blank=True, max_length=100, null=True)),
                ('picking_4', models.CharField(blank=True, max_length=100, null=True)),
                ('picking_5', models.CharField(blank=True, max_length=100, null=True)),
                ('picking_6', models.CharField(blank=True, max_length=100, null=True)),
                ('cost_ratio', models.CharField(blank=True, max_length=100, null=True)),
                ('farmer_feedback', models.TextField(blank=True, null=True)),
                ('success_stories', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
