# Generated by Django 5.0.6 on 2024-07-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigator_app', '0012_assessmentseason'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearlyProgressReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='', max_length=100)),
                ('date_field', models.DateField(blank=True, null=True)),
                ('physical_date', models.CharField(blank=True, max_length=100, null=True)),
                ('week', models.CharField(blank=True, max_length=100, null=True)),
                ('name_of_investigator', models.CharField(blank=True, max_length=100, null=True)),
                ('month', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('village', models.CharField(blank=True, max_length=100, null=True)),
                ('taluka', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('name_of_farmer', models.CharField(blank=True, max_length=100, null=True)),
                ('cultivation', models.BooleanField(choices=[(True, 'irrigated'), (False, 'rainfed')], default=False)),
                ('cultivation_feedback', models.TextField(blank=True, null=True)),
                ('spray_1_pesticide', models.CharField(blank=True, max_length=500, null=True)),
                ('spray_1_dose', models.FloatField(blank=True, null=True)),
                ('spray_1_target_pest', models.CharField(blank=True, max_length=500, null=True)),
                ('spray_2_pesticide', models.CharField(blank=True, max_length=500, null=True)),
                ('spray_2_dose', models.FloatField(blank=True, null=True)),
                ('spray_2_target_pest', models.CharField(blank=True, max_length=500, null=True)),
                ('spray_3_pesticide', models.CharField(blank=True, max_length=500, null=True)),
                ('spray_3_dose', models.FloatField(blank=True, null=True)),
                ('spray_3_target_pest', models.CharField(blank=True, max_length=500, null=True)),
                ('spray_4_pesticide', models.CharField(blank=True, max_length=500, null=True)),
                ('spray_4_dose', models.FloatField(blank=True, null=True)),
                ('spray_4_target_pest', models.CharField(blank=True, max_length=500, null=True)),
                ('spray_5_pesticide', models.CharField(blank=True, max_length=500, null=True)),
                ('spray_5_dose', models.FloatField(blank=True, null=True)),
                ('spray_5_target_pest', models.CharField(blank=True, max_length=500, null=True)),
                ('spray_6_pesticide', models.CharField(blank=True, max_length=500, null=True)),
                ('spray_6_dose', models.FloatField(blank=True, null=True)),
                ('spray_6_target_pest', models.CharField(blank=True, max_length=500, null=True)),
                ('spray_7_pesticide', models.CharField(blank=True, max_length=500, null=True)),
                ('spray_7_dose', models.FloatField(blank=True, null=True)),
                ('spray_7_target_pest', models.CharField(blank=True, max_length=500, null=True)),
                ('spray_8_pesticide', models.CharField(blank=True, max_length=500, null=True)),
                ('spray_8_dose', models.FloatField(blank=True, null=True)),
                ('spray_8_target_pest', models.CharField(blank=True, max_length=500, null=True)),
                ('spray_9_pesticide', models.CharField(blank=True, max_length=500, null=True)),
                ('spray_9_dose', models.FloatField(blank=True, null=True)),
                ('spray_9_target_pest', models.CharField(blank=True, max_length=500, null=True)),
                ('spray_10_pesticide', models.CharField(blank=True, max_length=500, null=True)),
                ('spray_10_dose', models.FloatField(blank=True, null=True)),
                ('spray_10_target_pest', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
