# Generated by Django 5.0.6 on 2024-07-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigator_app', '0013_yearlyprogressreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_servey_info',
            name='geolocations',
            field=models.CharField(blank=True, default='', max_length=900, null=True),
        ),
    ]
