# Generated by Django 5.0.6 on 2024-07-24 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investigator_app', '0014_alter_basic_servey_info_geolocations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basic_servey_info',
            name='soil_type',
        ),
    ]
