# Generated by Django 5.0.6 on 2024-07-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigator_app', '0015_remove_basic_servey_info_soil_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic_servey_info',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='basic_servey_info',
            name='landarea',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='basic_servey_info',
            name='soil_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
