# Generated by Django 5.0.6 on 2024-08-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigator_app', '0016_basic_servey_info_aadhar_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='standard_weeks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_number', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('standard_week', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
    ]
