# Generated by Django 5.0.6 on 2024-08-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigator_app', '0017_standard_weeks'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard_weeks',
            name='date_field',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='standard_weeks',
            name='year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
