# Generated by Django 5.0.6 on 2024-08-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigator_app', '0018_standard_weeks_date_field_standard_weeks_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard_weeks',
            name='month_data',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='standard_weeks',
            name='weeks_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
