# Generated by Django 5.0.6 on 2025-01-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigator_app', '0019_standard_weeks_month_data_standard_weeks_weeks_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_no', models.CharField(blank=True, default='', max_length=800, null=True)),
                ('date', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('month', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='news_articles/')),
            ],
        ),
    ]
