# Generated by Django 5.2.6 on 2026-08-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='farmer_photos/'),
        ),
    ]
