# Generated by Django 5.0.6 on 2024-06-17 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.CharField(db_index=True, default='', max_length=500, unique=True)),
                ('salutation', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('middle_name', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('designation', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('category', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=240, null=True, unique=True)),
                ('email_id', models.EmailField(blank=True, default='', max_length=700, null=True)),
                ('role_assign', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('joining_date', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('user_district', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=980, null=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=True)),
                ('is_user', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_farmer', models.BooleanField(default=False)),
                ('is_investigator', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='user_permissions_list', to='auth.permission')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.user')),
            ],
        ),
    ]
