# Generated by Django 5.0.6 on 2024-06-18 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_investigator_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigator_user',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
