# Generated by Django 5.0.6 on 2024-06-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_investigator_user_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigator_user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='investigator_user',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='investigator_user',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='investigator_user',
            name='state',
        ),
        migrations.AddField(
            model_name='investigator_user',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='investigator_user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='investigator_user',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='investigator_user',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='investigator_user',
            name='salutation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
