# Generated by Django 5.0.6 on 2024-06-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_remove_investigator_user_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='generated_pass',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
