# Generated by Django 5.0.6 on 2024-10-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_admin_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_en', models.CharField(blank=True, max_length=10, null=True)),
                ('week_hi', models.CharField(blank=True, max_length=10, null=True)),
                ('week_gu', models.CharField(blank=True, max_length=10, null=True)),
                ('date_range_en', models.CharField(blank=True, max_length=255, null=True)),
                ('date_range_hi', models.CharField(blank=True, max_length=255, null=True)),
                ('date_range_gu', models.CharField(blank=True, max_length=255, null=True)),
                ('month_en', models.CharField(blank=True, max_length=20, null=True)),
                ('month_hi', models.CharField(blank=True, max_length=20, null=True)),
                ('month_gu', models.CharField(blank=True, max_length=20, null=True)),
                ('start_date_en', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date_hi', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date_gu', models.CharField(blank=True, max_length=255, null=True)),
                ('pdf_path_en', models.CharField(blank=True, max_length=255, null=True)),
                ('pdf_path_hi', models.CharField(blank=True, max_length=255, null=True)),
                ('pdf_path_gu', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
