# Generated by Django 5.0.6 on 2024-10-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_advisory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisory',
            name='pdf_path_en',
        ),
        migrations.RemoveField(
            model_name='advisory',
            name='pdf_path_gu',
        ),
        migrations.RemoveField(
            model_name='advisory',
            name='pdf_path_hi',
        ),
        migrations.AddField(
            model_name='advisory',
            name='path_pdf_en',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='advisories/en/'),
        ),
        migrations.AddField(
            model_name='advisory',
            name='path_pdf_gu',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='advisories/gu/'),
        ),
        migrations.AddField(
            model_name='advisory',
            name='path_pdf_hi',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='advisories/hi/'),
        ),
    ]
