# Generated by Django 5.0.6 on 2025-07-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_remove_advisory_pdf_path_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisory',
            name='lang_1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='advisory',
            name='lang_1_pdf',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='advisories/'),
        ),
        migrations.AddField(
            model_name='advisory',
            name='lang_2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='advisory',
            name='lang_2_pdf',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='advisories/'),
        ),
        migrations.AddField(
            model_name='advisory',
            name='lang_3',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='advisory',
            name='lang_3_pdf',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='advisories/'),
        ),
        migrations.AddField(
            model_name='advisory',
            name='lang_4',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='advisory',
            name='lang_4_pdf',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='advisories/'),
        ),
        migrations.AddField(
            model_name='advisory',
            name='lang_5',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='advisory',
            name='lang_5_pdf',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='advisories/'),
        ),
        migrations.AddField(
            model_name='advisory',
            name='lang_6',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='advisory',
            name='lang_6_pdf',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='advisories/'),
        ),
        migrations.AddField(
            model_name='advisory',
            name='lang_7',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='advisory',
            name='lang_7_pdf',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='advisories/'),
        ),
    ]
