# Generated by Django 5.0.6 on 2025-07-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financial_Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
