# Generated by Django 5.0.6 on 2024-07-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pest_incidence_data',
            name='flowers_irm_average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pest_incidence_data',
            name='flowers_nonirm_average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pest_incidence_data',
            name='green_irm_average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pest_incidence_data',
            name='green_nonirm_average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pest_incidence_data',
            name='incidence_irm_average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pest_incidence_data',
            name='incidence_nonirm_average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pest_incidence_data',
            name='jassid_irm_average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pest_incidence_data',
            name='jassid_nonirm_average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pest_incidence_data',
            name='locular_damage_irm_average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pest_incidence_data',
            name='locular_damage_nonirm_average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pest_incidence_data',
            name='locule_irm_average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pest_incidence_data',
            name='locule_nonirm_average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pest_incidence_data',
            name='open_ball_irm_average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pest_incidence_data',
            name='open_ball_nonirm_average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pest_incidence_data',
            name='pheromone_irm_average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pest_incidence_data',
            name='pheromone_nonirm_average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pest_incidence_data',
            name='thrips_irm_average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pest_incidence_data',
            name='thrips_nonirm_average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pest_incidence_data',
            name='whitefly_irm_average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pest_incidence_data',
            name='whitefly_nonirm_average',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
