# Generated by Django 5.0.6 on 2024-07-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_settings', '0002_alter_pest_incidence_data_flowers_irm_average_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pest_incidence_data',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
