# Generated by Django 5.0.6 on 2024-07-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_settings', '0003_pest_incidence_data_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='pest_incidence_data',
            name='user_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
