# Generated by Django 5.0.6 on 2024-07-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_settings', '0004_pest_incidence_data_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='monthly_physical_progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='', max_length=100)),
                ('date_field', models.DateField(blank=True, null=True)),
                ('physical_date', models.CharField(blank=True, max_length=100, null=True)),
                ('week', models.CharField(blank=True, max_length=100, null=True)),
                ('name_of_investigator', models.CharField(blank=True, max_length=100, null=True)),
                ('month', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('pheromone_traps', models.CharField(blank=True, max_length=100, null=True)),
                ('splat', models.CharField(blank=True, max_length=100, null=True)),
                ('pb_rope', models.CharField(blank=True, max_length=100, null=True)),
                ('neem_insecticides', models.CharField(blank=True, max_length=100, null=True)),
                ('flonicamid', models.CharField(blank=True, max_length=100, null=True)),
                ('trichocards', models.CharField(blank=True, max_length=100, null=True)),
                ('quinalphos', models.CharField(blank=True, max_length=100, null=True)),
                ('chlorpyriphos', models.CharField(blank=True, max_length=100, null=True)),
                ('profenophos', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
