# Generated by Django 5.0.6 on 2024-07-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_settings', '0005_monthly_physical_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='extension_activities_carried_out',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='', max_length=100)),
                ('date_field', models.DateField(blank=True, null=True)),
                ('physical_date', models.CharField(blank=True, max_length=100, null=True)),
                ('week', models.CharField(blank=True, max_length=100, null=True)),
                ('name_of_investigator', models.CharField(blank=True, max_length=100, null=True)),
                ('month', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('popular_artical_number', models.CharField(blank=True, max_length=100, null=True)),
                ('popular_artical_beneficiary', models.CharField(blank=True, max_length=100, null=True)),
                ('press_release_number', models.CharField(blank=True, max_length=100, null=True)),
                ('press_release_beneficiary', models.CharField(blank=True, max_length=100, null=True)),
                ('extension_material_booklet_number', models.CharField(blank=True, max_length=100, null=True)),
                ('extension_material_booklet_beneficiary', models.CharField(blank=True, max_length=100, null=True)),
                ('extension_material_leaflet_number', models.CharField(blank=True, max_length=100, null=True)),
                ('extension_material_leaflet_beneficiary', models.CharField(blank=True, max_length=100, null=True)),
                ('extension_material_pamphlet_number', models.CharField(blank=True, max_length=100, null=True)),
                ('extension_material_pamphlet_beneficiary', models.CharField(blank=True, max_length=100, null=True)),
                ('extension_material_poster_number', models.CharField(blank=True, max_length=100, null=True)),
                ('extension_material_poster_beneficiary', models.CharField(blank=True, max_length=100, null=True)),
                ('literature_distributed_booklet_number', models.CharField(blank=True, max_length=100, null=True)),
                ('literature_distributed_booklet_beneficiary', models.CharField(blank=True, max_length=100, null=True)),
                ('literature_distributed_leaflet_number', models.CharField(blank=True, max_length=100, null=True)),
                ('literature_distributed_leaflet_beneficiary', models.CharField(blank=True, max_length=100, null=True)),
                ('literature_distributed_pamphlet_number', models.CharField(blank=True, max_length=100, null=True)),
                ('literature_distributed_pamphlet_beneficiary', models.CharField(blank=True, max_length=100, null=True)),
                ('voice_messages_number', models.CharField(blank=True, max_length=100, null=True)),
                ('voice_messages_beneficiary', models.CharField(blank=True, max_length=100, null=True)),
                ('field_visit_number', models.CharField(blank=True, max_length=100, null=True)),
                ('field_visit_beneficiary', models.CharField(blank=True, max_length=100, null=True)),
                ('farmer_mela_number', models.CharField(blank=True, max_length=100, null=True)),
                ('farmer_mela_beneficiary', models.CharField(blank=True, max_length=100, null=True)),
                ('exhibition_arranged_number', models.CharField(blank=True, max_length=100, null=True)),
                ('exhibition_arranged_beneficiary', models.CharField(blank=True, max_length=100, null=True)),
                ('farmer_training_number', models.CharField(blank=True, max_length=100, null=True)),
                ('farmer_training_beneficiary', models.CharField(blank=True, max_length=100, null=True)),
                ('training_number', models.CharField(blank=True, max_length=100, null=True)),
                ('training_beneficiary', models.CharField(blank=True, max_length=100, null=True)),
                ('tv_show_number', models.CharField(blank=True, max_length=100, null=True)),
                ('tv_show_beneficiary', models.CharField(blank=True, max_length=100, null=True)),
                ('radio_talks_numbers', models.CharField(blank=True, max_length=100, null=True)),
                ('radio_talks_beneficiary', models.CharField(blank=True, max_length=100, null=True)),
                ('sensitization_workshop_number', models.CharField(blank=True, max_length=100, null=True)),
                ('sensitization_workshop_beneficiary', models.CharField(blank=True, max_length=100, null=True)),
                ('farmers_queries_number', models.CharField(blank=True, max_length=100, null=True)),
                ('farmers_queries_beneficiary', models.CharField(blank=True, max_length=100, null=True)),
                ('lectures_delivered_number', models.CharField(blank=True, max_length=100, null=True)),
                ('lectures_delivered_beneficiary', models.CharField(blank=True, max_length=100, null=True)),
                ('news_clips_number', models.CharField(blank=True, max_length=100, null=True)),
                ('news_clips_beneficiary', models.CharField(blank=True, max_length=100, null=True)),
                ('visit_of_farmers_numbers', models.CharField(blank=True, max_length=100, null=True)),
                ('visit_of_farmers_beneficiary', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
