# Generated by Django 5.0.6 on 2024-07-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_settings', '0006_extension_activities_carried_out'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pest_incidence_data',
            old_name='locular_damage_irm',
            new_name='locular_damage_irm1',
        ),
        migrations.RenameField(
            model_name='pest_incidence_data',
            old_name='locular_damage_nonirm',
            new_name='locular_damage_irm10',
        ),
        migrations.AddField(
            model_name='pest_incidence_data',
            name='locular_damage_irm2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pest_incidence_data',
            name='locular_damage_irm3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pest_incidence_data',
            name='locular_damage_irm4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pest_incidence_data',
            name='locular_damage_irm5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pest_incidence_data',
            name='locular_damage_irm6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pest_incidence_data',
            name='locular_damage_irm7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pest_incidence_data',
            name='locular_damage_irm8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pest_incidence_data',
            name='locular_damage_irm9',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pest_incidence_data',
            name='locular_damage_nonirm1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pest_incidence_data',
            name='locular_damage_nonirm10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pest_incidence_data',
            name='locular_damage_nonirm2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pest_incidence_data',
            name='locular_damage_nonirm3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pest_incidence_data',
            name='locular_damage_nonirm4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pest_incidence_data',
            name='locular_damage_nonirm5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pest_incidence_data',
            name='locular_damage_nonirm6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pest_incidence_data',
            name='locular_damage_nonirm7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pest_incidence_data',
            name='locular_damage_nonirm8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pest_incidence_data',
            name='locular_damage_nonirm9',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
