# Generated by Django 5.0.6 on 2024-07-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_settings', '0007_rename_locular_damage_irm_pest_incidence_data_locular_damage_irm1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pest_incidence_data',
            name='standard_week',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
