# Generated by Django 5.0.6 on 2024-07-29 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner_settings', '0008_pest_incidence_data_standard_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extension_activities_carried_out',
            name='exhibition_arranged_beneficiary',
        ),
        migrations.RemoveField(
            model_name='extension_activities_carried_out',
            name='extension_material_booklet_beneficiary',
        ),
        migrations.RemoveField(
            model_name='extension_activities_carried_out',
            name='extension_material_leaflet_beneficiary',
        ),
        migrations.RemoveField(
            model_name='extension_activities_carried_out',
            name='extension_material_pamphlet_beneficiary',
        ),
        migrations.RemoveField(
            model_name='extension_activities_carried_out',
            name='extension_material_poster_beneficiary',
        ),
        migrations.RemoveField(
            model_name='extension_activities_carried_out',
            name='farmer_mela_beneficiary',
        ),
        migrations.RemoveField(
            model_name='extension_activities_carried_out',
            name='farmer_training_beneficiary',
        ),
        migrations.RemoveField(
            model_name='extension_activities_carried_out',
            name='farmers_queries_beneficiary',
        ),
        migrations.RemoveField(
            model_name='extension_activities_carried_out',
            name='field_visit_beneficiary',
        ),
        migrations.RemoveField(
            model_name='extension_activities_carried_out',
            name='lectures_delivered_beneficiary',
        ),
        migrations.RemoveField(
            model_name='extension_activities_carried_out',
            name='literature_distributed_booklet_beneficiary',
        ),
        migrations.RemoveField(
            model_name='extension_activities_carried_out',
            name='literature_distributed_leaflet_beneficiary',
        ),
        migrations.RemoveField(
            model_name='extension_activities_carried_out',
            name='literature_distributed_pamphlet_beneficiary',
        ),
        migrations.RemoveField(
            model_name='extension_activities_carried_out',
            name='news_clips_beneficiary',
        ),
        migrations.RemoveField(
            model_name='extension_activities_carried_out',
            name='popular_artical_beneficiary',
        ),
        migrations.RemoveField(
            model_name='extension_activities_carried_out',
            name='press_release_beneficiary',
        ),
        migrations.RemoveField(
            model_name='extension_activities_carried_out',
            name='radio_talks_beneficiary',
        ),
        migrations.RemoveField(
            model_name='extension_activities_carried_out',
            name='sensitization_workshop_beneficiary',
        ),
        migrations.RemoveField(
            model_name='extension_activities_carried_out',
            name='training_beneficiary',
        ),
        migrations.RemoveField(
            model_name='extension_activities_carried_out',
            name='tv_show_beneficiary',
        ),
        migrations.RemoveField(
            model_name='extension_activities_carried_out',
            name='visit_of_farmers_beneficiary',
        ),
        migrations.RemoveField(
            model_name='extension_activities_carried_out',
            name='voice_messages_beneficiary',
        ),
    ]
