# Generated by Django 5.0.6 on 2024-07-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_settings', '0009_remove_extension_activities_carried_out_exhibition_arranged_beneficiary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension_activities_carried_out',
            name='exhibition_arranged_beneficiary_female',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extension_activities_carried_out',
            name='exhibition_arranged_beneficiary_male',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extension_activities_carried_out',
            name='extension_material_booklet_beneficiary_female',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extension_activities_carried_out',
            name='extension_material_booklet_beneficiary_male',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extension_activities_carried_out',
            name='extension_material_leaflet_beneficiary_female',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extension_activities_carried_out',
            name='extension_material_leaflet_beneficiary_male',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extension_activities_carried_out',
            name='extension_material_pamphlet_beneficiary_female',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extension_activities_carried_out',
            name='extension_material_pamphlet_beneficiary_male',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extension_activities_carried_out',
            name='extension_material_poster_beneficiary_female',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extension_activities_carried_out',
            name='extension_material_poster_beneficiary_male',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extension_activities_carried_out',
            name='farmer_mela_beneficiary_female',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extension_activities_carried_out',
            name='farmer_mela_beneficiary_male',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extension_activities_carried_out',
            name='farmer_training_beneficiary_female',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extension_activities_carried_out',
            name='farmer_training_beneficiary_male',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extension_activities_carried_out',
            name='farmers_queries_beneficiary_female',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extension_activities_carried_out',
            name='farmers_queries_beneficiary_male',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extension_activities_carried_out',
            name='field_visit_beneficiary_female',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extension_activities_carried_out',
            name='field_visit_beneficiary_male',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extension_activities_carried_out',
            name='lectures_delivered_beneficiary_female',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extension_activities_carried_out',
            name='lectures_delivered_beneficiary_male',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extension_activities_carried_out',
            name='literature_distributed_booklet_beneficiary_female',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extension_activities_carried_out',
            name='literature_distributed_booklet_beneficiary_male',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extension_activities_carried_out',
            name='literature_distributed_leaflet_beneficiary_female',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extension_activities_carried_out',
            name='literature_distributed_leaflet_beneficiary_male',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extension_activities_carried_out',
            name='literature_distributed_pamphlet_beneficiary_female',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extension_activities_carried_out',
            name='literature_distributed_pamphlet_beneficiary_male',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extension_activities_carried_out',
            name='news_clips_beneficiary_female',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extension_activities_carried_out',
            name='news_clips_beneficiary_male',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extension_activities_carried_out',
            name='popular_artical_beneficiary_female',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extension_activities_carried_out',
            name='popular_artical_beneficiary_male',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extension_activities_carried_out',
            name='press_release_beneficiary_female',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extension_activities_carried_out',
            name='press_release_beneficiary_male',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extension_activities_carried_out',
            name='radio_talks_beneficiary_female',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extension_activities_carried_out',
            name='radio_talks_beneficiary_male',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extension_activities_carried_out',
            name='sensitization_workshop_beneficiary_female',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extension_activities_carried_out',
            name='sensitization_workshop_beneficiary_male',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extension_activities_carried_out',
            name='training_beneficiary_female',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extension_activities_carried_out',
            name='training_beneficiary_male',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extension_activities_carried_out',
            name='tv_show_beneficiary_female',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extension_activities_carried_out',
            name='tv_show_beneficiary_male',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extension_activities_carried_out',
            name='visit_of_farmers_beneficiary_female',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extension_activities_carried_out',
            name='visit_of_farmers_beneficiary_male',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extension_activities_carried_out',
            name='voice_messages_beneficiary_female',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extension_activities_carried_out',
            name='voice_messages_beneficiary_male',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
