# Generated by Django 5.0.6 on 2024-07-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_settings', '0010_extension_activities_carried_out_exhibition_arranged_beneficiary_female_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthly_physical_progress',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
